ARG ELIXIR_VERSION=1.20.2
ARG ERLANG_VERSION=29.0.2
ARG DEBIAN_VERSION=trixie-20260623-slim
ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${ERLANG_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:trixie-slim"

FROM ${BUILDER_IMAGE}

RUN apt-get update -y && apt-get install -y \
    build-essential \
    git \
    inotify-tools \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

ENV MIX_ENV=dev

# Install dependencies (these layers will be cached)
COPY mix.exs mix.lock ./
COPY apps/masaryk_ex/mix.exs apps/masaryk_ex/
COPY apps/masaryk_ex_web/mix.exs apps/masaryk_ex_web/
RUN mix deps.get

# The source code will be mounted as a volume
# so we don't COPY it here

EXPOSE 4000

CMD ["mix", "phx.server"]
